//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace RfidBus.Service.Location.Manager.database
{

    [OptimisticLocking(false)]
    [DeferredDeletion(false)]
    public partial class LocationParameters : XPObject
    {
        string fReader;
        public string Reader
        {
            get { return fReader; }
            set { SetPropertyValue<string>("Reader", ref fReader, value); }
        }
        int? fAntenna;
        public int? Antenna
        {
            get { return fAntenna; }
            set { SetPropertyValue<int?>("Antenna", ref fAntenna, value); }
        }
        Location fLocation;
        [Association(@"LocationParametersReferencesLocation")]
        public Location Location
        {
            get { return fLocation; }
            set { SetPropertyValue<Location>("Location", ref fLocation, value); }
        }
    }

}
